grpc:
  port: 6565
spring:
  profiles:
    active: local
  r2dbc:
    url: r2dbc:h2:mem:///test
    username: sa
    password:
    pool:
      enabled: true
  datasource:
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework.r2dbc: DEBUG

app:
  config:
    aws:
      sdk:
        region: us-west-2
        profile: ${spring.profiles.active}