server:
  port: 8888

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/demo?reWriteBatchedInserts=true
    username: postgres
    password: password
    pool:
      enabled: true
debug: true

logging:
  level:
    org.springframework: INFO
    org.springframework.transaction: DEBUG
    org.springframework.r2dbc: DEBUG

app:
  config:
    aws:
      sdk:
        region: us-west-2
        profile: ${spring.profiles.active}
    sender: no-reply@crscube.io