DROP TABLE IF EXISTS MSG_EMAIL;
CREATE TABLE MSG_EMAIL (
    EMAIL_KEY SERIAL NOT NULL,
    MSG_ID VARCHAR(256) NOT NULL,
    SENDER VARCHAR(256) NOT NULL,
    SUBJECT VARCHAR(512) NOT NULL,
    CONTENT TEXT NOT NULL,
    SENT_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (EMAIL_KEY)
);
